### ISSUE TITLE
Win 10+anaconda python3.9.16，AttributeError: module 'openalea.strawberry' has no attribute 'import_mtgfile'

### ISSUE THREAD

**Issue by longwangtang** [openalea/strawberry#89]
运行如下代码时候报错：
import openalea.mtg as mtg
from oawidgets.plantgl import PlantGL
import openalea.strawberry as strawberry

g = strawberry.import_mtgfile.import_mtgfile(filename= ["Capriss"])
g.properties()['order'] = mtg.algo.orders(g)
scene=straberry.visu3d.plot3d(g,by=["Sample_date"],hide_leaves=False,display=False)
PlantGL(scene, group_by_color=True)

**Comment by pradal** [comment]
How do you install strawberry?
Can you report the command:

    conda info --all

**Comment by pradal** [comment]
The code was not valid. Here is a working example:

```python
from openalea.mtg.algo import orders
from oawidgets.plantgl import PlantGL
from openalea.strawberry import visu3d
from openalea.strawberry.import_mtgfile import import_mtgfile

g = import_mtgfile(filename= ["Capriss"])
g.properties()['order'] = orders(g)
scene=visu3d.plot3d(g,by=["Sample_date"],hide_leaves=False,display=False)
PlantGL(scene, group_by_color=True)
```
